title: Cripto-Eduar
description: Educación sobre Criptomonedas
baseurl: ""  # Si usas GitHub Pages con /docs, déjalo vacío
url: "https://tusuario.github.io"  # Tu URL de GitHub Pages

# Jekyll
plugins:
  - jekyll-data
  - jekyll-sitemap

# Opcional (usaremos datos de _data/)
defaults:
  - scope:
      path: ""
    values:
      layout: default
